"""
Django settings for social_media_data_analyse_system project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import warnings
warnings.filterwarnings("ignore")
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%an6-gqv&n9v)*&h4988i-9$w5dxiv(^9w_f&y$cb7$fdw@)ua'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'scrapy_monitor',
    'data_model',
    'scrapy_test',
    'djcelery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # '“7django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social_media_data_analyse_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        'libraries': {  # Adding this section should work around the issue.
            'staticfiles': 'django.templatetags.static',
            },
        },
    },

]

WSGI_APPLICATION = 'social_media_data_analyse_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'social_database',
        'USER': 'root',
        'PASSWORD': 'buptweb007',
        'HOST': '152.136.59.62',
        'PORT': '3307',
        'OPTIONS': {'charset': 'utf8mb4'}
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'templates/scrapy_display/static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static/'),
)


#celery设置
from celery.schedules import crontab,timedelta
import djcelery
djcelery.setup_loader()
BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'

CELERYD_CONCURRENCY = 1
CELERY_IMPORTS = ('scrapy_test.tasks','scrapy_monitor.tasks')
CELERY_TIMEZONE = TIME_ZONE
#CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

from celery.schedules import crontab
CELERYBEAT_SCHEDULE = {
    #定时任务一：　定时获取cookie
    u'定时获取cookie': {
        "task": "scrapy_monitor.tasks.timed_cookies",
        "schedule": crontab(hour='*/3',minute=0),
        "args": (),
    },
    u'定时爬虫启动': {
        "task": "scrapy_monitor.tasks.timed_task",
        "schedule": crontab(hour='*/3',minute=20),
        "args": (),
    },
    u'定时爬取新浪新闻': {
        "task": "scrapy_monitor.tasks.xinlang_task",
        "schedule": crontab(hour='*/3',minute=30),
        "args": (),
    }

}
