# Generated by Django 3.0.3 on 2020-10-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo_post',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weibo_user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
