# Generated by Django 3.0.3 on 2020-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xinlang_manage',
            fields=[
                ('task_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('scrapy_id', models.CharField(blank=True, max_length=500, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('range', models.CharField(blank=True, max_length=10, null=True)),
                ('date_time_begin', models.CharField(blank=True, max_length=500, null=True)),
                ('date_time_end', models.CharField(blank=True, max_length=500, null=True)),
                ('real_time_task', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'xinlang_manage',
            },
        ),
        migrations.CreateModel(
            name='xinlang_new',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('brief', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('detail_link', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'xinlang_new',
                'unique_together': {('task_id', 'news_id')},
            },
        ),
    ]
