# Generated by Django 3.0.3 on 2020-08-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0002_xinlang_manage_xinlang_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xinlang_new',
            old_name='news_id',
            new_name='post_id',
        ),
        migrations.AlterUniqueTogether(
            name='xinlang_new',
            unique_together={('task_id', 'post_id')},
        ),
    ]
